### ISSUE TITLE
Enable "Always Display in Console" If user is in Restricted Group

### ISSUE THREAD

**Issue by elmidwill** [sventorben/keycloak-restrict-client-auth#101]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

When a users signs in to keycloak I would like to have them see all the applications they have access to without having to login to the site first and create a session.

### Describe the solution you'd like

Hello,

I would like to know if it is possible to enable "Always Display in Console" option in the client settings if the user is a member of the restricted group?  If I am not able to do it with the keycloak-restrict-client-auth, can you recommend another approach, whether  programmatically or otherwise.

Much appreciated.  

### Describe alternatives you've considered

I thought about enabling "Always Display in Console" for all apps, customizing the accounts page using something like Javascript and hide the icon if the user is not in the restricted group.

**Comment by sventorben** [comment]
Hello @elmidwill ,

thanks for suggesting this enhancement. Unfortunately, it is currently not possible to with this extension and I do not see a way to implement this in a general way. To my knowledge, Keycloak does not provide an SPI or extension point to support this. Also it would not be trivial to detect whether a user is allowed to use a client or not, because that heavily depends on the authentication flow configuration.

Maybe in you special case it could be possible to build a custom solution by providing a REST APi endpoint. You may want to check the [Developer Guide](https://www.keycloak.org/docs/latest/server_development/#_extensions_rest) on how to do this.
You may want to implement some logic to lookup the [authenticator config](https://github.com/sventorben/keycloak-restrict-client-auth/blob/v19.0.0/src/main/java/de/sventorben/keycloak/authorization/client/RestrictClientAuthConfig.java#L27) in your authentiction flow. The `RestrictClientAuthConfig` holds a property `getAccessProviderId()` the returns the id of the [`AccessProvider`](https://github.com/sventorben/keycloak-restrict-client-auth/blob/main/src/main/java/de/sventorben/keycloak/authorization/client/access/AccessProvider.java) used by the authenticator. You may then lookup the `AccessProvider`:
```java
AccessProvider accessProvider = keycloakSession.getProvider(AccessProvider.class, accessProviderId);
// Check if access to client is restricted
accessProvider.isRestricted(clientModel);

// Check if access for a user is permitted
accessProvider.isPermitted(clientModel, userModel);
```

Maybe you can work out something from there. 

Regards
Sven-Torben

**Comment by elmidwill** [comment]
Sorry for the late reply, can you elaborate a little?

**Comment by sventorben** [comment]
I am suggesting that you build a custom extension. You will have to customize the account console to filter out some of your clients. You may provide a REST API as part of your extensions which tries to determine to which clients a user has access. Provide that list of accessible clients to the account console (frontend) and show the clients to your users. You will have to decide which clients are accessible to the user and which are not. For this you can use the SPI as mentioned in my previous comment (https://github.com/sventorben/keycloak-restrict-client-auth/issues/101#issuecomment-1211240020)
