### ISSUE TITLE
[BUG] Not authorized users can authenticate in client

### ISSUE THREAD

**Issue by klunk66** [sventorben/keycloak-restrict-client-auth#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an user will be log in at a client that isn't authorized, the Keycloak deny the access, but if this user log in a client that are been authorized, this same user can log in everyone client while the session is valid.

### Expected Behavior

The role validation must be run in everyone authentication maked by user

### Version

```markdown
- Keycloak: 19.0.1
- This extension: 19.0.0
```

**Comment by sventorben** [comment]
Can you please post you flow configuration? It may be a misconfiguration in combination with the cookie authenticator.

**Comment by klunk66** [comment]
Yes, follows.

![image](https://user-images.githubusercontent.com/37509723/185932558-4047c0a3-7e2b-49f7-a413-43ede5be3ef0.png)

**Comment by sventorben** [comment]
The behaviour that you experience is not an issue of this authenticator. It's due to how your flow is configured.

If a user is not authenticated, the `Cookie` authenticator will be skipped, because no SSO cookie exists.
`Kerberos` authenticator will be skipped as well, because it is disabled.
`Identity provider redirector` will most likely also be skipped. 
Last alternative is `2FA forms` subflow.

If the user logs in to a client that is not restricted, the `Restrict user authentication on clients` authenticator will return successfully. The user will be logged in and a SSO cookie will be set.

Now, if afterwards the user tries to login to a restricted client, a cookie is present and the first alternative (the `Cookie` authenticator) will return successfully. Since it is an alternative, no further authenticators or subflows will be executed.

Please make sure to configure the authenticator as described in the [README.md](https://github.com/sventorben/keycloak-restrict-client-auth#how-to-configure) (see [this picture](https://github.com/sventorben/keycloak-restrict-client-auth/blob/main/docs/images/flow.jpg)).

Alternatively, [this issue](https://github.com/sventorben/keycloak-restrict-client-auth/issues/9#issuecomment-937059969) could serve as a good example for your use case.
