### ISSUE TITLE
[BUG] Restriction with an Identity Provider appears to be non-functional

### ISSUE THREAD

**Issue by mdurand54** [sventorben/keycloak-restrict-client-auth#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am configuring the access restriction. I have no problem restricting access using `Username Password Form`. However, as soon as I use the configured identity provider, the restriction never applies.

### Expected Behavior

The same operation between the Username/password connection and the identifty provider connection.

### Steps To Reproduce

Here is the connection flow I have:

![image](https://user-images.githubusercontent.com/1679489/197259209-1e7f4674-52be-44da-901e-ec13777c3cf4.png)

### Version

```markdown
- Keycloak: 19.0.1 (quarkus)
- This extension: 19.0.0
```

### Anything else?

I searched through the existing issues, I did not find a clue to solve my problem. Sorry if this is the case.

I also wondered about "is this prodider supposed to work with an Identity Provider?". The only answer I could find in the README is [here](https://github.com/sventorben/keycloak-restrict-client-auth#why-not-use-allowdeny-access-authenticators-with-conditions). And it just says, that this provider is better than the "Allow/Deny Access" feature which doesn't work with identity providers.

In any case, thank you for your work!

**Comment by sventorben** [comment]
Hello @mdurand54,

thanks for reporting this.
I am afraid this is an issue with sub-flows and authenticators in combination with identity provider redirection in general and not limited to this authenticator.

You will have to configure [post login flow](https://www.keycloak.org/docs/latest/server_admin/index.html#_general-idp-config) for every identity provider.

This has also already been discussed in [KEYCLOAK-19538](https://issues.redhat.com/browse/KEYCLOAK-19538) and seems to be by design.

Best regards
Sven-Torben

**Comment by mdurand54** [comment]
Oh okay. Thanks for the explanation. 

So, I'm trying to configure a post login flow. Would it make sense to keep only the cookie and the authenticator part post login flow. Something like:

- Login (required)
    - Cookie (required)
- Restrict user authentication on clients -> (required)

**Comment by mdurand54** [comment]
Effectively, the extension is sufficient in the post login flow. 

Thank you very much for your help!

**Comment by mdurand54** [comment]
Effectively, the extension is sufficient in the post login flow.

Thank you very much for your help!
