### ISSUE TITLE
No access denied when access is denied

### ISSUE THREAD

**Issue by dmgeurts** [sventorben/keycloak-restrict-client-auth#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Managed to get it to do what it needs to do: Grant access by IdP group and block access to other IdP users. But when a user doesn't have access the login page refreshes instead of showing an access-denied page

### Expected Behavior

I was expecting to see an error of sorts so a user knows not to enter their credentials again in vain.

### Steps To Reproduce

1. Install Keycloak 19.0.3
2. Install the jar file to the providers folder and run build
3. Follow the rest of the instructions and verify that valid users are granted access while others and blocked.

### Version

```markdown
- Keycloak: 19.0.3
- This extension: 19.0.0
```

### Anything else?

As I'm new to Keycloak it's quite possible that my issue is simply user error.

**Comment by sventorben** [comment]
Hello @dmgeurts,

you are right, you should see an error message.

Can you please post a screenshot of your flow configuration?

Best regards
Sven-Torben

**Comment by dmgeurts** [comment]
Hi @sventorben,

Good to know, my flow is:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/2071992/197986440-2f08d05f-6790-440f-a5d7-a3f715667059.png">

Thanks,
Djerk

**Comment by dmgeurts** [comment]
Playing around with this I now find that the restriction is no longer working... _sigh_

**Comment by dmgeurts** [comment]
My browser flow looks slightly different, from the one in the installation instructions. I figured I'd recreate the flow to see if that would make a difference, but it doesn't:

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/2071992/197999232-9b16cf5a-73b9-4e50-99ec-a5626ee0ff7a.png">

But somehow I don't think this is the issue.

**Comment by sventorben** [comment]
Your configuration in https://github.com/sventorben/keycloak-restrict-client-auth/issues/116#issuecomment-1291804071 cannot work, because you cannot mix required and alternative flows/executions on the same level. Please see https://github.com/sventorben/keycloak-restrict-client-auth/issues/9#issuecomment-937059969 for a detailed explanation.

**Comment by dmgeurts** [comment]
And that solves the issue of the missing access denied page.

Thank you!

**Comment by dmgeurts** [comment]
As a side note, I had also missed setting the new flow as the default for the realm.

**Comment by sventorben** [comment]
Good to hear that it is working for you.

To bind a default flow, you need to open the flow under `Configure -> Authentication -> Flows (tab)` and then use the actions menu in the upper right corner:
![image](https://user-images.githubusercontent.com/12183470/198087347-985a9f96-cd5f-4b74-bae3-26f65b89bf62.png)

The bug is already knwo and expected to be fixed with Keycloak 20.0.0 (see https://github.com/sventorben/keycloak-restrict-client-auth/issues/107 for details).
