### ISSUE TITLE
[BUG] Access provider list is empty

### ISSUE THREAD

**Issue by flo-mic** [sventorben/keycloak-restrict-client-auth#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed the extension on a new keycloak docker instance from jboss/keycloak

When i try to configure the extension i can not select an „Access Provider“ as the field shows no entries. 

### Expected Behavior

The Access Provider list should display the correct options

### Steps To Reproduce

1. Add the extension to a fresh keycloak instance
2. Edit the extension
3. The Access Provider field is empty

### Version

```markdown
- Keycloak: 15.0.2
- This extension: 15.1.0
```

**Comment by sventorben** [comment]
Hey @flo-mic,
thanks for checking out the latest pre-release and reporting this issue.

This issue generally occurs if you install the extension by mounting/copying the jar to `/opt/jboss/keycloak/standalone/deployments` instead of `/opt/jboss/keycloak/providers`.
This has changed from version 15.0.0 to 15.1.0. 

Please double check that you have mounted/copied the jar file to the correct location.

Thanks
Sven-Torben

**Comment by flo-mic** [comment]
Thanks, this was my fault. It is working now.

**Comment by battosai30** [comment]
I had the same issue with Keycloak 16.1.0 and v16.0.0 of the plugin.

For the record (and Java/Keycloak noobs like me) : 
```
mkdir KEYCLOAK_HOME/providers
cd providers
wget https://github.com/sventorben/keycloak-restrict-client-auth/releases/download/v16.0.0/keycloak-restrict-client-auth.jar
```
Of course, change KEYCLOAK_HOME to the root folder where Keycloak is installed, and change wget link to the package's version you need
